/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rayhanashlikh.proyekakhiruas.Product;

import com.rayhanashlikh.proyekakhiruas.Customer.FormCustomer;
import com.rayhanashlikh.proyekakhiruas.FormLoginNew;
import com.rayhanashlikh.proyekakhiruas.KoneksiMySQL;
import com.rayhanashlikh.proyekakhiruas.Main.FormMain;
import com.rayhanashlikh.proyekakhiruas.Orders.FormOrders;
import com.rayhanashlikh.proyekakhiruas.Seller.FormSellers;
import java.awt.Container;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Rayhan
 */
public class StockProduct extends javax.swing.JFrame {

    Connection con;
    Statement stm;
    ResultSet rs;
    String current_id;
    Container container;

    /**
     * Creates new form UpdateProduct
     */
    public StockProduct(String current_id) {
        initComponents();
        open_db();
        this.current_id = current_id;
        set_text();
        titleLabel.setText("Product");
        subTitleLabel.setText("Admin/Product/Management Stock Product");
        navHome.setBackground(new java.awt.Color(8, 64, 214));
        navProducts.setBackground(new java.awt.Color(80, 117, 243));
        navProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MouseListener[] mouseListeners = navProducts.getMouseListeners();
        for (MouseListener ml : mouseListeners) {
            navProducts.removeMouseListener(ml);
        }
        PlainDocument doc = (PlainDocument) txtStok.getDocument();
        doc.setDocumentFilter(new MyIntFilter());
    }

    public StockProduct() {
        initComponents();
    }

    private void open_db() {
        try {
            KoneksiMySQL kon = new KoneksiMySQL("localhost", "root",
                    "", "batikraft_new");
            con = kon.getConnection();
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }

    private void set_text() {
        try {
            stm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            String sql = "SELECT * FROM barang WHERE id=" + current_id + " LIMIT 1;";
//            System.out.println(sql);
            rs = stm.executeQuery(sql);
            while (rs.next()) {
                txtId.setText(rs.getString("id"));
                txtNama.setText(rs.getString("nama"));
                txtStokSekarang.setText(rs.getString("jumlah"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupStok = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        navHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        navSeller = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        navOrders = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        navProducts = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        navCustomers = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        subTitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        radMasuk = new javax.swing.JRadioButton();
        radKeluar = new javax.swing.JRadioButton();
        txtStokSekarang = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(8, 36, 161));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Admin Dashboard");
        sidepane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 180, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 200, 10));

        navHome.setBackground(new java.awt.Color(80, 117, 243));
        navHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navHomeMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Home.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");

        javax.swing.GroupLayout navHomeLayout = new javax.swing.GroupLayout(navHome);
        navHome.setLayout(navHomeLayout);
        navHomeLayout.setHorizontalGroup(
            navHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navHomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        navHomeLayout.setVerticalGroup(
            navHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(navHomeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidepane.add(navHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 50));

        navSeller.setBackground(new java.awt.Color(8, 98, 210));
        navSeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navSellerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navSellerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navSellerMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Small Business.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seller");

        javax.swing.GroupLayout navSellerLayout = new javax.swing.GroupLayout(navSeller);
        navSeller.setLayout(navSellerLayout);
        navSellerLayout.setHorizontalGroup(
            navSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navSellerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        navSellerLayout.setVerticalGroup(
            navSellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navSellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navSellerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
        );

        sidepane.add(navSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, -1));

        navOrders.setBackground(new java.awt.Color(8, 64, 214));
        navOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navOrdersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navOrdersMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Shopping Cart.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Orders");

        javax.swing.GroupLayout navOrdersLayout = new javax.swing.GroupLayout(navOrders);
        navOrders.setLayout(navOrdersLayout);
        navOrdersLayout.setHorizontalGroup(
            navOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navOrdersLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        navOrdersLayout.setVerticalGroup(
            navOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navOrdersLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(14, 14, 14))
        );

        sidepane.add(navOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        navProducts.setBackground(new java.awt.Color(8, 64, 214));
        navProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navProductsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navProductsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navProductsMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Cardboard Box.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Products");

        javax.swing.GroupLayout navProductsLayout = new javax.swing.GroupLayout(navProducts);
        navProducts.setLayout(navProductsLayout);
        navProductsLayout.setHorizontalGroup(
            navProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navProductsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        navProductsLayout.setVerticalGroup(
            navProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navProductsLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );

        sidepane.add(navProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        navCustomers.setBackground(new java.awt.Color(8, 64, 214));
        navCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navCustomersMouseExited(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Users.png")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Customers");

        javax.swing.GroupLayout navCustomersLayout = new javax.swing.GroupLayout(navCustomers);
        navCustomers.setLayout(navCustomersLayout);
        navCustomersLayout.setHorizontalGroup(
            navCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navCustomersLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        navCustomersLayout.setVerticalGroup(
            navCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navCustomersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navCustomersLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(14, 14, 14))
        );

        sidepane.add(navCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 620));

        jPanel1.setBackground(new java.awt.Color(81, 155, 232));

        subTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        subTitleLabel.setText("Home");

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Admin Dashboard");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Logout.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Kuliah\\Semester 4\\UAS\\ProyekAkhirUAS\\src\\icon\\Back Arrow.png")); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(378, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subTitleLabel)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subTitleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(titleLabel)
                .addGap(27, 27, 27))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 760, 140));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 30));

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Id Product");

        txtId.setEditable(false);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Nama Produk");

        txtNama.setEditable(false);
        txtNama.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Jenis Transaksi Stok");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Jumlah Stok");

        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 123, 255));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        groupStok.add(radMasuk);
        radMasuk.setText("Stok Masuk");
        radMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMasukActionPerformed(evt);
            }
        });

        groupStok.add(radKeluar);
        radKeluar.setText("Stok Keluar");

        txtStokSekarang.setEditable(false);
        txtStokSekarang.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Stok Produk Sekarang");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel18)
                        .addComponent(txtId)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addComponent(radMasuk)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(radKeluar))
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addComponent(txtStok)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNama)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStokSekarang)))
                .addGap(24, 24, 24))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStokSekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(radMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSimpan)
                .addGap(63, 63, 63))
        );

        bg.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 750, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHomeMouseClicked
        FormMain main = new FormMain();
        main.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_navHomeMouseClicked

    private void navHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHomeMouseEntered
        setColor(navHome);
    }//GEN-LAST:event_navHomeMouseEntered

    private void navHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navHomeMouseExited
        resetColor(navHome);
    }//GEN-LAST:event_navHomeMouseExited

    private void navSellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navSellerMouseClicked
        FormSellers seller = new FormSellers();
        seller.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_navSellerMouseClicked

    private void navSellerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navSellerMouseEntered
        setColor(navSeller);
    }//GEN-LAST:event_navSellerMouseEntered

    private void navSellerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navSellerMouseExited
        resetColor(navSeller);
    }//GEN-LAST:event_navSellerMouseExited

    private void navOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navOrdersMouseClicked
        FormOrders orders = new FormOrders();
        orders.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_navOrdersMouseClicked

    private void navOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navOrdersMouseEntered
        setColor(navOrders);
    }//GEN-LAST:event_navOrdersMouseEntered

    private void navOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navOrdersMouseExited
        resetColor(navOrders);
    }//GEN-LAST:event_navOrdersMouseExited

    private void navProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navProductsMouseClicked
        FormProducts products = new FormProducts();
        products.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_navProductsMouseClicked

    private void navProductsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navProductsMouseEntered
        setColor(navProducts);
    }//GEN-LAST:event_navProductsMouseEntered

    private void navProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navProductsMouseExited
        resetColor(navProducts);
    }//GEN-LAST:event_navProductsMouseExited

    private void navCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCustomersMouseClicked
        FormCustomer customer = new FormCustomer();
        customer.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_navCustomersMouseClicked

    private void navCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCustomersMouseEntered
        setColor(navCustomers);
    }//GEN-LAST:event_navCustomersMouseEntered

    private void navCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCustomersMouseExited
        resetColor(navCustomers);
    }//GEN-LAST:event_navCustomersMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        FormLoginNew login = new FormLoginNew();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        FormProducts formProducts = new FormProducts();
        formProducts.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String opsi = getSelectedButton();
        String stok = txtStok.getText();

        boolean pass_validation = true;
        ArrayList<String> msg = new ArrayList<String>();

        if (opsi.isEmpty()) {
            pass_validation = false;
            msg.add("Input jenis transaksi stok tidak boleh kosong");
        }

        if (stok.isEmpty()) {
            pass_validation = false;
            msg.add("Input jumlah stok tidak boleh kosong");
        }

        try {
            if (pass_validation == true) {
                if (opsi.equals("Stok Masuk")) {
                    stm = con.createStatement();
                    String sql = "UPDATE barang SET jumlah=jumlah + " + stok + ""
                            + " WHERE id='" + current_id + "'";
                    stm.executeUpdate(sql);
                    
                    LocalDate now = LocalDate.now();
                    String save = "INSERT INTO stock_updates VALUES(default, "
                            + current_id + ", 'masuk', "+ stok +", '"+ now +"');";
//                    System.out.println(save);
                    stm.executeUpdate(save);
                    
                    JOptionPane.showMessageDialog(null, "Tambah Stok Produk berhasil");
                    FormProducts products = new FormProducts();
                    products.setVisible(true);

                    this.dispose();
                } else {
                    stm = con.createStatement();
                    String sql = "UPDATE barang SET jumlah=jumlah - " + stok + ""
                            + " WHERE id='" + current_id + "'";
                    stm.executeUpdate(sql);
                    
                    LocalDate now = LocalDate.now();
                    String save = "INSERT INTO stock_updates VALUES(default, "
                            + current_id + ", 'keluar', "+ stok +", '"+ now +"');";
//                    System.out.println(save);
                    stm.executeUpdate(save);
                    
                    JOptionPane.showMessageDialog(null, "Kurangi Stok Produk berhasil");
                    FormProducts products = new FormProducts();
                    products.setVisible(true);

                    this.dispose();
                }
            } else {
                String message = "";
                for (String i : msg) {
                    message += "• " + i + "\n";
                }

                JOptionPane.showMessageDialog(null, message);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void radMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radMasukActionPerformed

    void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(8, 98, 210));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(8, 64, 214));
    }

    String getSelectedButton() {
        for (Enumeration<AbstractButton> buttons = groupStok.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel content;
    private javax.swing.ButtonGroup groupStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel navCustomers;
    private javax.swing.JPanel navHome;
    private javax.swing.JPanel navOrders;
    private javax.swing.JPanel navProducts;
    private javax.swing.JPanel navSeller;
    private javax.swing.JRadioButton radKeluar;
    private javax.swing.JRadioButton radMasuk;
    private javax.swing.JPanel sidepane;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtStokSekarang;
    // End of variables declaration//GEN-END:variables
}

class MyIntFilter extends DocumentFilter {

    @Override
    public void insertString(FilterBypass fb, int offset, String string,
            AttributeSet attr) throws BadLocationException {

        Document doc = fb.getDocument();
        StringBuilder sb = new StringBuilder();
        sb.append(doc.getText(0, doc.getLength()));
        sb.insert(offset, string);

        if (test(sb.toString())) {
            super.insertString(fb, offset, string, attr);
        } else {
            // warn the user and don't allow the insert
        }
    }

    private boolean test(String text) {
        try {
            Integer.parseInt(text);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    @Override
    public void replace(FilterBypass fb, int offset, int length, String text,
            AttributeSet attrs) throws BadLocationException {

        Document doc = fb.getDocument();
        StringBuilder sb = new StringBuilder();
        sb.append(doc.getText(0, doc.getLength()));
        sb.replace(offset, offset + length, text);

        if (test(sb.toString())) {
            super.replace(fb, offset, length, text, attrs);
        } else {
            // warn the user and don't allow the insert
        }

    }

    @Override
    public void remove(FilterBypass fb, int offset, int length)
            throws BadLocationException {
        Document doc = fb.getDocument();
        StringBuilder sb = new StringBuilder();
        sb.append(doc.getText(0, doc.getLength()));
        sb.delete(offset, offset + length);

        if (test(sb.toString())) {
            super.remove(fb, offset, length);
        } else {
            // warn the user and don't allow the insert
        }

    }
}
